### ISSUE TITLE
使用后添加了重复的域名

### ISSUE THREAD

**Issue by ydx1013** [naicfeng/hexo-filter-links#1]
使用后在markdown里面添加了重复的域名，导致404错误。

如。    https://www.taobao.com/https://www.taobao.com/go/#aHR0cHM6Ly9zsG9wMTI5NzUwNjg0LnRdjdJhby5jb340=

**Comment by naicfeng** [comment]
能看一下你原始的markdown是怎么写的吗

**Comment by naicfeng** [comment]
太长时间没有下文
